### ISSUE TITLE
Support providing account hashes as an alternative to public keys throughout the casper-client where this makes sense

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-client-rs#55]
Some of the subcommands (e.g. `get-account`) which currently only support providing a public key should be enhanced to support providing an account hash instead.  For reference, see how this is handled in `query-balance`.

**Comment by bpr** [comment]
There needs to be 

1. A change in casper node ./node/src/components/rpc_server/rpcs/state.rs, where GetAccountInfoParams is defined, to handle the logic of a PurseIdentifier instead of a public key. 

2. Doc and maybe other changeto support a modified client api, and JSON rpc call, if we're changing state_get_acount_info, which backs get-account.

I've already made all of the changes in client, which is in review.

**Comment by RitaMAllenCA** [comment]
I've talked with Fraser about the ticket and we've discovered that changes are still needed on the node to update the RPC handler for state_get_account_info.
I just wanted to check where this work would be in the pipeline for the core team.
Additionally, If it makes sense for the timelines on the core team, Fraser and I discussed potentially pairing to get those changes made. Rita, if Fraser can spare some cycles and you approve, I would love the opportunity!
@RBYGLLS
